import type { Metadata } from "next"
import localFont from "next/font/local"

import "./globals.css"

import { Suspense } from "react"
import Sidebar from "@/components/sidebar"

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} flex font-sans antialiased`}>
        <Suspense fallback={<div className="sticky top-0 h-screen w-64" />}>
          <Sidebar />
        </Suspense>
        <main className="grow bg-gray-50">{children}</main>
      </body>
    </html>
  )
}
